#!/bin/bash

source ~/.config/lemonbar/setup

while true; do
echo "$(mpd) %{r} $(battery) $SEP $(wifi_ssid) $SEP $(volume) $SEP %{B$BACKGROUND_COLOR} %{F$WIFI_COLOR} $SEP $(printf '%b' "\uf073") %{F$FOREGROUND_COLOR} $(date +'%A, %b %d') %{F$WIFI_COLOR} $SEP $(printf '%b' "\uf017") %{F$FOREGROUND_COLOR} $(date +'%I:%M') $SEP %{B F-}"
    sleep 1s
done |

lemonbar\
    -b\
    -g "1920x30"\
    -f "$FONT1" -f "$FONT2"\
    -F "$FOREGROUND_COLOR" | bash
