#!/bin/bash

source ~/.config/lemonbar/setup

while true; do
echo "$(mpd)%{r}$(battery) $SEP $(wifi_ssid) $SEP $(volume)  %{B$YELLOW_COLOR}  %{F$WIFI_COLOR}$(printf '%b' "\uf073") %{F$BACKGROUND_COLOR} $(date +'%A, %b %d')  %{B$FOREGROUND_COLOR} %{F$WIFI_COLOR} $(printf '%b' "\uf017") %{F$BACKGROUND_COLOR} $(date +'%H:%M')  %{B F-}"
    sleep 1s
done |

lemonbar\
    -b\
    -g "2560x30"\
    -f "$FONT1" -f "$FONT2"\
    -B "$FOREGROUND_COLOR" \
    -F "$BACKGROUND_COLOR" | bash
