#!/bin/bash

FONT1="Source Sans Pro:size=8"
FONT2="FontAwesome:size=10"

BACKGROUND_COLOR="#c5c8c6"
FOREGROUND_COLOR="#1d1f21"

COLOR1="#ffcc6666"
COLOR2="#ffb5bd68"
COLOR3="#ff969896"

BLACK_COLOR="#000000"
RED_COLOR="#333333"
GREEN_COLOR="#333333"
YELLOW_COLOR="#2a2a2a"
BLUE_COLOR="#268bd2"
BAT_COLOR="#cc6666"
MAGENTA_COLOR="#d33682"
CYAN_COLOR="#2aa198"
WHITE_COLOR="#FFFFFF"
WIFI_COLOR="#b5bd68"

SEP=""

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


volume(){
    VOLUME=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[1]}')
    MUTE=$(pulseaudio-ctl full-status | awk '{split($0, array, " ")} END{print array[2]}')
    if [ "$MUTE" == "yes" ]; then
        echo "%{F$RED_COLOR A:pulseaudio-ctl mute:}$(printf '%b' "\uf026") $VOLUME%%{A F-}"
    else
	echo "%{F$BLUE_COLOR A:pulseaudio-ctl mute:}$(printf '%b' "\uf027")%{F-} $VOLUME%%{A}"
    fi
}

mpd(){
    STATUS=$(mpc current)
    echo "%{F$BLUE_COLOR A:mpc toggle: A3:mpc stop:} $(printf '%b' "\uf001") %{F-} $STATUS%{A A}"
}


wifi_ssid(){
    NAME=$(iwconfig wlp2s0 | grep 'ESSID:' | awk '{print $4}' | sed 's/ESSID://g' | sed 's/"//g')
	if [ "$NAME" != "" ]; then
	    if [ "$NAME" == "off/any" ]; then
	        echo "%{F$RED_COLOR}$(printf '%b' "\uf05e")%{F-} no conn"
	    else echo "%{F$WIFI_COLOR}$(printf '%b' "\uf1eb")%{F-} $NAME"
	    fi
	fi
}

battery() {
	BATTERY=$(~/bin/battery.sh)
	if [ "$BATTERY" != "%" ]; then
    	echo "%{F$BAT_COLOR}$(printf '%b' "\uf1e6")%{F-} $BATTERY"
	fi
}

load_avg() {
    AVGLOAD=$(cut -d " " -f 1-3 /proc/loadavg)
    echo "%{F$BLUE_COLOR}$(printf '%b' "\f0ae")%{F-} $AVGLOAD"
}
