#!/bin/bash

FONT2="Terminus:size=10"
FONT1="FontAwesome:size=10"

BACKGROUND_COLOR="#FF2A303B"
FOREGROUND_COLOR="#FFb3bdcb"

COLOR1="#ffcc6666"
COLOR2="#ffb5bd68"
COLOR3="#ff969896"

BLACK_COLOR="#000000"
RED_COLOR="#999999"
GREEN_COLOR="#669966"
YELLOW_COLOR="#2a2a2a"
BLUE_COLOR="#268bd2"
BAT_COLOR="#cc6666"
MAGENTA_COLOR="#d33682"
CYAN_COLOR="#2aa198"
WHITE_COLOR="#FFFFFF"
WIFI_COLOR="#b5bd68"

SEP=""

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


volume(){
    VOLUME=$(awk -F"[][]" '/dB/ { print $2 }' <(amixer get Master))
    if amixer get Master | grep -q off; then
        echo "%{F$RED_COLOR A:amixer sset Master unmute:}$(printf '%b' "\uf026") $VOLUME%{A F-}"
    else
	echo "%{F$BLUE_COLOR A:amixer sset Master mute:}$(printf '%b' "\uf028")%{F-} $VOLUME%{A}"
    fi
}

mpd(){
    STATUS=$(mpc current)
    echo "%{F$BLUE_COLOR A:mpc toggle: A3:mpc stop:} $SEP $(printf '%b' "\uf001") %{F-} $STATUS%{A A}"
}


wifi_ssid(){
    NAME=$(iwgetid -r)
	IP=$(ip addr | grep wlp2s0 | sed -n 's/.*inet.\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
	if [ "$NAME" != "" ]; then
	    echo "%{F$WIFI_COLOR}$(printf '%b' "\uf1eb")%{F-} $NAME"
	fi
}

battery() {
	BATTERY=$(~/bin/battery.sh)
	if [ "$BATTERY" != "%" ]; then
		if acpi -a | grep -q on; then
    		echo "%{F$GREEN_COLOR}$(printf '%b' "\uf1e6")%{F-} $BATTERY"
		else
			echo "%{F$BAT_COLOR}$(printf '%b' "\uf1e6")%{F-} $BATTERY"
		fi
	fi
}

load_avg() {
    AVGLOAD=$(cut -d " " -f 1-3 /proc/loadavg)
    echo "%{F$BLUE_COLOR}$(printf '%b' "\f0ae")%{F-} $AVGLOAD"
}
